theme:
  name: material
site_name: winsonYe
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: index.md
  - 开发: 
    - 计算机基础:
      - 操作系统
      - 计算机网络
      - 计算机组成原理
      - 数据结构与算法
      - Linux: computer_basic/Linux.md 
      - Git: computer_basic/Git.md
    - 前端开发:
      - WebAssembly: software_development/frontend/WebAssembly.md
    - 后端开发: 
      - MySQL: software_development/backend/MySQL.md
      - Redis: software_development/backend/Redis.md
      - Kafka: software_development/backend/Kafka.md
      - 消息队列: software_development/backend/MessageQueue.md
      - 分布式系统
      - DevOps:
        - Docker: software_development/backend/DevOps/Docker.md
        - k8s
        - tomcat
      - 语言: 
        - C++: software_development/backend/language/C++.md
        - Rust: software_development/backend/language/Rust.md
        - Java: software_development/backend/language/Java.md
        - Go: software_development/backend/language/Go.md
      - 面经: software_development/backend/interview_experiences.md      
      - 项目:
        - 工程问题: software_development/backend/Project/project_knowledge.md      
        - 逸仙东华资源共享平台: software_development/backend/Project/逸仙东华/project_review.md
    - 软件测试: 
      - 理论知识: software_development/software_test/software_test_theory.md
  - 算法题: 
    - 算法基础: algorithm/algorithm_basic.md
    - leetcode刷题笔记: algorithm/leetcode.md
  - 杂谈:
    - Mac的一些问题: util/Mac.md
  - About: about.md

